#cutable files for this directory
OBJECTS = arith-ex arraysizeof cond \
		  incr int-div oofe overflow \
		  prec shift-prec sizeof_pgm \
		  unaryOps vec_init warn_dbltoint

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and  files
include ../GNU_makefile_template

LOCFLAGS = -I../2
