#.outcutable files for this directory
OBJECTS = arith-ex.out arraysizeof.out cond.out \
		  incr.out int-div.out oofe.out overflow.out \
		  prec.out shift-prec.out sizeof_pgm.out \
		  unaryOps.out vec_init.out warn_dbltoint.out

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .out files
include ../GNU_makefile_template

LOCFLAGS = -I../2
