#cutable files for this directory
OBJECTS = capacity erase1 erase2 find_ops \
		  find-str refreshIter stack \
		  str_assignOps substr useConvs

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and  files
include ../GNU_makefile_template

LOCFLAGS = -I..\7

