#.outcutable files for this directory
OBJECTS = capacity.out erase1.out erase2.out find_ops.out \
		  find-str.out refreshIter.out stack.out \
		  str_assignOps.out substr.out useConvs.out

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .out files
include ../GNU_makefile_template

LOCFLAGS = -I..\7

