#.outcutable files for this directory
OBJECTS = add_using.out arrayScores.out cctype.out \
		  char_repl.out cstring_hdr.out getline.out \
		  hexify.out multidim.out \
		  ptr_traversal2.out square.out strcompare.out \
		  string_add.out string_io.out string_io2.out \
		  string_size.out string_size2.out string_size3.out \
		  vec_decls.out vecStrings2.out vecScores.out \
		  vecSubs.out word_echo.out

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .out files
include ../GNU_makefile_template

LOCFLAGS = -I../1
