#cutable files for this directory
OBJECTS = add_using arrayScores cctype \
		  char_repl cstring_hdr getline \
		  hexify multidim \
		  ptr_traversal2 square strcompare \
		  string_add string_io string_io2 \
		  string_size string_size2 string_size3 \
		  vec_decls vecStrings2 vecScores \
		  vecSubs word_echo

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and  files
include ../GNU_makefile_template

LOCFLAGS = -I../1
