CCFLAGS = -W -Wall -I..
#cutable files for this directory
OBJECTS = add add_item add_item2 avg_price \
		  for_ex forcount item_io \
		  main_only mysum occurs whilecount 

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and  files
include ../GNU_makefile_template

add_item add_item2 avg_price item_io: Sales_item.h
