CCFLAGS = -W -Wall -I..
#.outcutable files for this directory
OBJECTS = add.out add_item.out add_item2.out avg_price.out \
		  for_ex.out forcount.out item_io.out \
		  main_only.out mysum.out occurs.out whilecount.out 

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .out files
include ../GNU_makefile_template

add_item.out add_item2.out avg_price.out item_io.out: Sales_item.h
