#.outcutable files for this directory
OBJECTS = absInt.out accum.out accum4.out \
		  avg_price.out bind2.out elimDups.out equal.out \
		  equiv-istream-iter.out inserters.out \
		  iostream_iter.out newcount-size.out \
		  ostreamIter2.out rcomma.out \
		  reverse.out reverse-iter.out rev-iters.out \
		  sortSI.out use_find.out use-istream-iter.out

# the corresponding source file uses c++ 11 features
C11_OBJECTS = lambda.out 

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .out files
include ../GNU_makefile_template

LOCFLAGS = -I../1 -I../6

