#cutable files for this directory
OBJECTS = absInt accum accum4 \
		  avg_price bind2 elimDups equal \
		  equiv-istream-iter inserters \
		  iostream_iter newcount-size \
		  ostreamIter2 rcomma \
		  reverse reverse-iter rev-iters \
		  sortSI use_find use-istream-iter

# the corresponding source file uses c++ 11 features
C11_OBJECTS = lambda 

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and  files
include ../GNU_makefile_template

LOCFLAGS = -I../1 -I../6

