#.outcutable files for this directory
OBJECTS = add_item2.out doWhile.out guess.out ifgrades.out \
		  othercnt.out rangefor.out vowels.out 

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .out files
include ../GNU_makefile_template

LOCFLAGS = -I../1

