#cutable files for this directory
OBJECTS = add_item2 doWhile guess ifgrades \
		  othercnt rangefor vowels 

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and  files
include ../GNU_makefile_template

LOCFLAGS = -I../1

