#cutable files for this directory
OBJECTS = compounddecls convs dbl_ptr \
		  escape inits \
		  literals ref-ex Sales_data \
		  scope_levels unsigned

# thesecutables are not made by default;
# the corresponding source file uses c++ 11 features
C11_OBJECTS = decl-ex

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and  files
include ../GNU_makefile_template

LOCFLAGS = -I../1
