#.outcutable files for this directory
OBJECTS = compounddecls.out convs.out dbl_ptr.out \
		  escape.out inits.out \
		  literals.out ref-ex.out Sales_data.out \
		  scope_levels.out unsigned.out

# these.outcutables are not made by default;
# the corresponding source file uses c++ 11 features
C11_OBJECTS = decl-ex.out

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .out files
include ../GNU_makefile_template

LOCFLAGS = -I../1
